### ISSUE TITLE
无法清除样式

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/insider#1045]
加粗加斜后，点击清除样式无法清除
![image](https://user-images.githubusercontent.com/46953371/190915028-aeb59b3c-6400-4ec5-8fd8-ad9e8813f15a.png)

**Comment by Vanessa219** [comment]
清除样式是单独放在颜色里面的，没有放在工具栏上，用这个来清除斜体、粗体等其他样式可能有点不太合适。

**Comment by mozhux** [comment]
这个之前发现了，得单独点击对应的样式取消。这个清除样式主要清除的颜色的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月19日 8:48
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [siyuan-note/insider] 无法清除样式 (Issue #1045)


清除样式是单独放在颜色里面的，没有放在工具栏上，用这个来清除斜体、粗体等其他样式可能有点不太合适。

―

**Comment by Vanessa219** [comment]
嗯，那等再看看有没有其他用户有这个需求，有的话可能需要挪到工具栏上来才行。

**Comment by mozhux** [comment]
有新用户提了，对于一个行级内的元素，不能一键全选清除样式，每个都需要选中后再去点对应样式，所以还是希望能把清除样式的按钮放到工具栏，给一个橡皮擦的图标

**Comment by mozhux** [comment]
这个基本上云端文档类都有的。
如企业微信
***@***.***
钉钉
***@***.***
语雀
***@***.***


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月20日 21:41
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [siyuan-note/insider] 无法清除样式 (Issue #1045)


看了一下其他笔记，好想没有类似的功能。是不是这样的实际使用场景比较少呢？

―

**Comment by 88250** [comment]
我也觉得还是支持一下比较好 :trollface:

**Comment by 88250** [comment]
补充说明：行级代码、行级公式和键盘等带有明确语义的元素不会清除。

**Comment by mozhux** [comment]
啊这。。清除格式就是只保留纯文本啊。。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月21日 11:05
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [siyuan-note/insider] 支持清除行级元素样式 (Issue #1045)


补充说明：行级代码、行级公式和键盘等带有明确语义的元素不会清除。

―

**Comment by 88250** [comment]
你看下语雀上面也是这样设计的。

**Comment by mozhux** [comment]
好像也有道理，这些东西清除格式了就是奇怪的文本了。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月21日 11:08
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [siyuan-note/insider] 支持清除行级元素样式 (Issue #1045)


你看下语雀上面也是这样设计的。

―

**Comment by 88250** [comment]
是的，这样设计是合理的，只清除样式类型（粗体斜体颜色这些），不清除语义类型。
