### ISSUE TITLE
无法取消备注

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/insider#1046]
不想备注的时候没有取消的入口，建议备注内容为空的时候是取消状态。
![image](https://user-images.githubusercontent.com/46953371/190915113-1513e98d-dd30-4604-8437-8fbbdfdaca13.png)

**Comment by Zuoqiu-Yingyi** [comment]
希望划选备注锚文本后悬浮工具栏也可以高亮, 以及再次点击备注按钮时取消, 这样和其他元素保持一致
![image](https://user-images.githubusercontent.com/49649786/191173214-21fdad34-09c9-449e-bef5-d9d6fe8046bf.png)
备注还有两个问题
- 默认的快捷键 <kbd>Ctrl+Alt+M</kbd> 是无效的, 既不能插入元素, 也不能将划选内容转化为备注/取消备注
- 将快捷键更改为其他快捷键也是无效的, 且在重新设置为 <kbd>Ctrl+Alt+M</kbd> 时提示 `快捷键无效`
