### ISSUE TITLE
上标和下标不能同时存在

### ISSUE THREAD

**Issue by a1751504** [siyuan-note/insider#1049]
现在的情况是两个能同时选择，都选择后固定为上标，逻辑上来说应该是只能单选
![image](https://user-images.githubusercontent.com/31113826/190915700-c40356b9-9e94-4955-9736-cbcd4f74c0b3.png)

**Comment by Vanessa219** [comment]
选中是用户的行为，点击图标后会根据图标的状态对选中的元素进行对应的删减。
