### ISSUE TITLE
既然支持备注了，希望能支持外框备注，从而实现类admonition功能

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/insider#1051]
如题，希望可以借鉴专注笔记的实现方式，有这种外框备注演示，从而实现类似admonition功能
![image](https://user-images.githubusercontent.com/46953371/190916017-cb1c1d5f-5ce5-41d7-bc2c-70511f121c89.png)

**Comment by 88250** [comment]
这个是块级的吧？

**Comment by mozhux** [comment]
> 这个是块级的吧？
是的，既然都能嵌套了，看能不能支持一下？

@88250

**Comment by 88250** [comment]
这个后面再考虑吧，不太确定通过主题 CSS 是否能实现。
