### ISSUE TITLE
标记无法隐藏

### ISSUE THREAD

**Issue by a1751504** [siyuan-note/insider#1052]
![image](https://user-images.githubusercontent.com/31113826/190916447-726d7ba1-8b71-4949-bbd0-4db451974077.png)
![image](https://user-images.githubusercontent.com/31113826/190916489-e65d451b-4efc-4854-a89a-50587c9a0291.png)

**Comment by Vanessa219** [comment]
隐藏指的是取消标记么？再点一下就可以取消了。

**Comment by a1751504** [comment]
> 隐藏指的是取消标记么？再点一下就可以取消了。

这是主题的功能，是我搞错了，不好意思

**Comment by a1751504** [comment]
另外，比如我给十个文字打上了标记，只要选中其中的一部分文字（哪怕是一个字符）并按下标记键就可以就取消这十个文字的标记，
而现在是只取消选中的那几个文字的标记，
相当于想要取消标记得选中所有的已标记文字，万一这个标记有很多行上百字呢？还是之前的版本更符合逻辑，望修改一下
@Vanessa219

**Comment by Vanessa219** [comment]
标记和粗体、斜体等一样，会对选中的内容做相反的操作。当想取消上百字中的某些字不为标记时就会比较方便。
