### ISSUE TITLE
表格块不支持使用快捷键 `Ctrl+C` 与块菜单项 `复制` 进行复制

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/insider#1055]

**Comment by 88250** [comment]
我这里测试正常。

**Comment by Zuoqiu-Yingyi** [comment]
频繁偶发, 我再找找复现规律。。。

**Comment by Zuoqiu-Yingyi** [comment]
> 我这里测试正常。

找到文档复现步骤了
1. 光标定位到表格内
2. 连续按两次 <kbd>Shift + ↑</kbd>, 选中该表格
3. 此时使用快捷键 <kbd>Ctrl + C</kbd> 或块菜单的 <kbd>复制</kbd> 按钮无法复制

注: 除了`复制`, 貌似其他功能是正常的
