### ISSUE TITLE
光标定位到行级元素内部时粘贴为纯文本不应带标记符和样式

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/insider#1057]
光标定位到行内元素内部时使用快捷键粘贴会将该元素从光标处一分为二截断，并在分裂的两个元素之间插入内容

使用粘贴为纯文本也会出现该情况

**Comment by 88250** [comment]
这个目前是这样设计的，粘贴时拆分元素。

**Comment by Zuoqiu-Yingyi** [comment]
> 这个目前是这样设计的，粘贴时拆分元素。

粘贴为纯文本时是否应该不拆分元素❓

**Comment by Vanessa219** [comment]
@88250 BlockDOM2StdMd 返回错误
