### ISSUE TITLE
PDF 渲染错误

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/insider#1060]
![image](https://user-images.githubusercontent.com/16383685/190960916-09794c93-f5f9-4449-b18e-5158a692e2f2.png)
![image](https://user-images.githubusercontent.com/16383685/190960951-82e5f1c5-bb92-44bd-878d-46d4c917e291.png)

**Comment by 88250** [comment]
`上` 和 `发` 上面的是行级备注，看上去好像没有问题。

**Comment by woniuxia** [comment]
奥奥 是我的问题
不过有另外一个问题`上`和`发`现在有下划线 但是 pdf 没有，D大看下这个符合预期吗
![image](https://user-images.githubusercontent.com/16383685/190961269-e90cf10e-159f-4754-8546-ff7ebf81eeaa.png)

![image](https://user-images.githubusercontent.com/16383685/190961403-c18310ca-4d93-4436-917f-196ba533b367.png)

**Comment by 88250** [comment]
已经转换为上班了，目前看是符合预期的。这个细节等正式版后面上线以后看看是否有其他用户提，有的话我们再考虑修改。
