### ISSUE TITLE
无法使用SQL来查询

### ISSUE THREAD

**Issue by lvzhp** [siyuan-note/insider#1062]
之前的查询内容 已经无法显示了。

**Comment by lvzhp** [comment]
之前使用插件 ：query进行查询，现在再次查询，无法显示了， 语法是正确的，也无法显示了

**Comment by 88250** [comment]
可能是这个问题 https://github.com/siyuan-note/insider/issues/1053

我先关闭了，等下个版本发布以后重建索引再试试，如果还有问题请跟帖。
