### ISSUE TITLE
希望能多选块加样式

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/insider#1063]
如题，老版本不支持多选块添加加粗，下划线等操作，新版希望能增加支持，最好是可以批量多选已加载的块

**Comment by Vanessa219** [comment]
这个只是针对行级元素的操作，针对块级的操作需要后期统一添加到块级菜单上。

**Comment by mozhux** [comment]
> 这个只是针对行级元素的操作，针对块级的操作需要后期统一添加到块级菜单上。

主要是针对多块的批量行级操作，比如多选两个块中的某些字加粗啥的

**Comment by Vanessa219** [comment]
你说的这个应该是和块级菜单中的关外差不多。

**Comment by mozhux** [comment]
> 你说的这个应该是和块级菜单中的外观差不多。

现在块级菜单也基本都是单个操作，不支持多选批量处理，操作上麻烦许多
