### ISSUE TITLE
行级元素不同的情况下备注，备注会生成多个

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/insider#1068]
如题，如果一段话里有加粗有颜色，选中这一段备注，备注会按照行级元素加粗，颜色分别生成备注，而不是选中的一段来生成。
应该要按选中的来生成，否则搜索结果也会错乱，会有多个匹配。
![mmexport1663650797727.png](https://user-images.githubusercontent.com/46953371/191173325-40b7a58a-f008-411a-ba0b-1cf948909ceb.png)

**Comment by 88250** [comment]
这个是特性，和其他行级元素一样，如果有多个叠加的话会自动拆分。

**Comment by mozhux** [comment]
这个拆分出来的目的是啥呢？都是同一个备注，不管他们是谁，我都是对他们统一进行的备注

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月20日 15:36
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [siyuan-note/insider] 行级元素不同的情况下备注，备注会生成多个 (Issue #1068)


这个是特性，和其他行级元素一样，如果有多个叠加的话会自动拆分。

―

**Comment by 88250** [comment]
不同的样式从逻辑上来说已经不是同一个实体了，所以单独拆分开更符合预期。
