### ISSUE TITLE
行内元素 `行内代码` 与 `键盘` 在行末时使用快捷键跳出异常

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/insider#1069]
复现步骤:
1. 将光标从其他行通过鼠标点击定位到行末为 `行内代码` 或 `键盘` 元素的行的末尾
2. 使用快捷键跳出(使用任何行内元素的快捷键都会出现该问题)
3. 此时会分割出一个空的 `行内代码` 或 `键盘` 元素, 如下所示

![image](https://user-images.githubusercontent.com/49649786/191174667-c9f2d544-499f-418f-b55f-64c40c4e4be9.png)
![image](https://user-images.githubusercontent.com/49649786/191174692-2490cf19-f197-4a35-a692-b02c7f4694ee.png)

**Comment by Zuoqiu-Yingyi** [comment]
同时还发现, 删除下图的 `1` 字符会导致两个行内代码合并
![image](https://user-images.githubusercontent.com/49649786/191175369-2f9c4e5c-9dfd-4162-ab9b-3348bcc8ea7d.png)

**Comment by 88250** [comment]
我这里重现不了，你看这个重现操作是否正确：

![issue](https://user-images.githubusercontent.com/873584/191198379-3b6daa66-b9cb-4ff3-a83d-791ac7029611.gif)



> 同时还发现, 删除下图的 `1` 字符会导致两个行内代码合并 ![image](https://user-images.githubusercontent.com/49649786/191175369-2f9c4e5c-9dfd-4162-ab9b-3348bcc8ea7d.png)

这个是保留之前版本的特性，自动合并两个相邻的行级代码。

**Comment by Zuoqiu-Yingyi** [comment]
> 我这里重现不了，你看这个重现操作是否正确：
> 
> ![issue](https://user-images.githubusercontent.com/873584/191198379-3b6daa66-b9cb-4ff3-a83d-791ac7029611.gif)

这里已经重现了
![image](https://user-images.githubusercontent.com/49649786/191208593-82dd50b7-1ce8-46cb-8577-657ad34b0445.png)
```html
<span data-type="code">foo</span>
&ZeroWidthSpace;
<span data-type="code"></span>
```

**Comment by Vanessa219** [comment]
这个是已经跳出了，直接输入就可。再按一下就又生成了新的代码块。由于中间是零宽空格，输入后空格消失，再输入就会合并了。
