### ISSUE TITLE
公式输入的逻辑问题

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/insider#1072]
![Screenshot_2022-09-20-18-00-57-749_org b3log siyuan-edit](https://user-images.githubusercontent.com/32903588/191230139-7f3df865-7140-4333-b12b-6462db6e2ab6.jpg)
上图代码分三行，我回车换行了，但是第二行和第三行之间没有空格，如果连在一起会报错，现在这么写不会报错
，编辑完成保存后如下图
![Screenshot_2022-09-20-18-01-35-176_org b3log siyuan-edit](https://user-images.githubusercontent.com/32903588/191230689-fe0c76a9-47cd-4cb6-a6f6-96bdb3eee13d.jpg)
自动处理，消除了换行，这下有错了，但依旧不报错
![Screenshot_2022-09-20-18-02-05-375_org b3log siyuan-edit](https://user-images.githubusercontent.com/32903588/191230945-bb17269a-d9db-4da0-9290-2bbab37fe816.jpg)
关闭文档重新打开就报错了，这下对了

问题就是该报错的时候没报，以为没问题的时候又报错了，这部分逻辑能否优化一下，比如自动处理后加空格或者加换行啥的，或者直接报错，体验不会这么撕裂

**Comment by Vanessa219** [comment]
行内数学公式不允许换行，不知道把所有的换行转换为空格会不会有问题？
先处理为关闭后报错。

**Comment by TinkMingKing** [comment]
加入空格不会报错，改成加入空格会更合理一点，主要是让字母分开就没问题了
