### ISSUE TITLE
数据解析时未区分超链接与图片

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/insider#1073]
该问题在如下多个方面体现
- 数据库 `spans` 表中 `type` 为 `textmark a` 的记录 `markdown` 字段均为 `![foo](bar)` 样式
- 数据库 `blocks` 表中 `markdown` 字段内的超链接均为 `![foo](bar)` 样式
- 使用 API `/api/export/exportMdContent` 返回的所有超链接也均为图片链接的形式
- 使用 API `/api/block/getBlockKramdown` 返回的所有超链接也均为图片链接形式

**Comment by 88250** [comment]
此外，图片元素不再使用 `link_text` 和 `link_dest` 子节点，而是使用 `img` 作为元素类型。
