### ISSUE TITLE
使用快捷键 `Shift+↑` 选中某个块后使用快捷键 `Ctrl+/` 唤起选中块的块菜单失效

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/insider#1075]
经测试, 当光标处于某个行级元素内时, 无论是使用 <kbd>Shift + ↑</kbd> 选择该行级元素所在的叶子块, 还是多次使用  <kbd>Shift + ↑</kbd> 选择该行级元素所在的容器块, <kbd>Ctrl + /</kbd> 唤起的菜单均为行级元素的菜单, 应该是这个原因导致选中某个块后 <kbd>Ctrl + /</kbd> 唤起块菜单失效

**Comment by Vanessa219** [comment]
哈哈，就在刚刚我也发现这个问题了。

**Comment by Zuoqiu-Yingyi** [comment]
现在这个问题修复了, 但是貌似光标在非行内元素的普通文本处使用 <kbd>Ctrl+/</kbd> 激活光标所在叶子块的块菜单功能还没修复👀

**Comment by Vanessa219** [comment]
求截图或录屏

**Comment by Zuoqiu-Yingyi** [comment]
> 求截图或录屏

现在只有选中块后才能使用 <kbd>ctrl+/</kbd> 唤起块菜单, `2.1.14` 使用 <kbd>ctrl+/</kbd> 能选中光标所在叶子块并唤起块菜单
![思源笔记-bug反馈-40](https://user-images.githubusercontent.com/49649786/191541299-2b761463-b642-4b8a-ad13-d38f74d84a97.gif)

**Comment by Vanessa219** [comment]
多谢
