### ISSUE TITLE
改进清除样式图标

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/insider#1078]
建议清除样式给橡皮擦图标，不是现在垃圾桶的

**Comment by 88250** [comment]
https://ant.design/components/icon/ 这里好像没有橡皮擦的，我们换成这个吧：

![image](https://user-images.githubusercontent.com/873584/191637743-d26cfbb9-0005-4a41-a0cc-3a88ec24de85.png)

**Comment by mozhux** [comment]
要不上这里的看下。新标签页 (xicons.org)<https://www.xicons.org/#/> 谷歌的啥的都有

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月22日 9:22
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [siyuan-note/insider] 清除样式建议用那个橡皮擦的图标 (Issue #1078)


https://ant.design/components/icon/ 这里好像没有橡皮擦的，我们换成这个吧：

[image]<https://user-images.githubusercontent.com/873584/191637743-d26cfbb9-0005-4a41-a0cc-3a88ec24de85.png>

―
