### ISSUE TITLE
在反链面板里转换段落块类型后出现状态异常

### ISSUE THREAD

**Issue by Dammyxy** [siyuan-note/insider#1084]
1.在反链面板里无法通过点击触发段落块块菜单
2.在反链面板里通过快捷键唤出段落块块菜单后，对其进行转换后会出现状态异常
![在反链面板里将段落块转换为列表块后出现状态异常](https://user-images.githubusercontent.com/48867926/193635532-ee502fd9-540c-4672-9a36-0923a605043b.gif)

**Comment by 88250** [comment]
我们这里无法重现第一个问题（1.在反链面板里无法通过点击触发段落块块菜单）。

**Comment by Dammyxy** [comment]
> 我们这里无法重现第一个问题（1.在反链面板里无法通过点击触发段落块块菜单），试下默认主题？

环境：默认主题无自定义外观
版本：2.30 A1
部分段落块出现无法通过点击唤出块菜单的问题，不止在反链面板内，在正文里也有，后来发现是这类点不开块菜单的段落块字数不够换行，如下图：
![换行后能唤出菜单](https://user-images.githubusercontent.com/48867926/193769376-fc934743-130e-405a-af06-0718e2ec3f95.gif)

**Comment by 88250** [comment]
我们这里还是重现不了。

**Comment by lfsjack** [comment]
在zhanglight主题里，无法弹出菜单时会出现一个白条。
![Snipaste_2022-10-07_09-53-32](https://user-images.githubusercontent.com/29227663/194450535-6dcd90af-9919-4ddd-b29a-a597ad5a34aa.png)
打开控制台报错如下。
![image](https://user-images.githubusercontent.com/29227663/194450095-499da1f5-5edb-4c73-a2eb-b28cfb4e8412.png)
另外，有个疑似能稳定复现的办法，就是在反链面板通过ctrl/alt/shift+click打开新文档。
不知道你们那里按照这个办法能不能稳定复现

**Comment by 88250** [comment]
@lfsjack 默认主题下正常吗？

**Comment by lfsjack** [comment]
> @lfsjack 默认主题下正常吗？

这个bug似乎和主题无关，因为每次无法弹出菜单时我切到默认主题都依然有问题，而能正常弹出菜单时切换主题并不会导致bug重新出现。大概率是和反链面板有关系，因为每次重新出现这个bug都是在反链面板里进行了某个操作后出现的。因为在a1a2中这个bug是延迟出现的，所以具体是啥操作无法确定，之前怀疑是ctrl+click点标题打开新文档导致的，但是a3中进行这个操作数次后并没有复现bug。

**Comment by 88250** [comment]
@lfsjack 好的，我们先调整了再看看，谢谢。
