### ISSUE TITLE
当块引用与所引用内容位于同一个文档时，块引用与所引用的内容块进行交换功能异常

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/insider#1085]
[块引用与所引用的内容块进行交换 · Issue #4981 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/4981)

当块引用与所引用内容位于同一个文档时, 例如ID为 `20221004010437-7ahtpnf` 的块引用了自己位于同一篇文档的ID为 `20221004010434-id3sjxx` 的块, 那么ID为 `20221004010437-7ahtpnf` 的块无论是 `转换为定义块` 还是 `转换为定义块及其子快` 操作, 都会由于 ID 的变动, 导致块引用所在块与被引用所在块的 ID 发生改变, 进而出现两个无效引用, 如下所示

**转换前**
```markdown
11111
{: id="20221004010434-id3sjxx" updated="20221004010436"}

((20221004010434-id3sjxx '11111'))
{: id="20221004010437-7ahtpnf" updated="20221004010441"}
```

**转换后**
```markdown
((20221004010434-id3sjxx '11111'))
{: id="20221004010437-7ahtpnf" updated="20221004010441"}

((20221004010434-id3sjxx '11111'))
{: id="20221004010519-c1p04fc" updated="20221004010441"}
```

**Comment by Zuoqiu-Yingyi** [comment]
同时, 引用标题块时应交换标题块及其下级内容

**Comment by 88250** [comment]
> 同时, 引用标题块时应交换标题块及其下级内容

这个我这里测试在不同文档中表现正常，估计需要你再描述一下细节。

**Comment by Zuoqiu-Yingyi** [comment]
> 这个我这里测试在不同文档中表现正常，估计需要你再描述一下细节。

就是标题块应该将标题及其下级块一块转换过来, 而非只是标题块一个块
![image](https://user-images.githubusercontent.com/49649786/193742853-ac40b642-3122-4ff5-a8e1-8f8652985d68.png)

**Comment by 88250** [comment]
> > 这个我这里测试在不同文档中表现正常，估计需要你再描述一下细节。
> 
> 就是标题块应该将标题及其下级块一块转换过来, 而非只是标题块一个块 ![image](https://user-images.githubusercontent.com/49649786/193742853-ac40b642-3122-4ff5-a8e1-8f8652985d68.png)

选择那个带子级移动的应该没问题吧。

**Comment by Zuoqiu-Yingyi** [comment]
> 选择那个带子级移动的应该没问题吧。

经过测试，对于标题块的引用，两个菜单项效果一致，都不能移动子级

**Comment by 88250** [comment]
是不是块引用所在段落是在引用的定义标题块下方，如果是的话交换以后本身就是子级了。

**Comment by Zuoqiu-Yingyi** [comment]
> 是不是块引用所在段落是在引用的定义标题块下方，如果是的话交换以后本身就是子级了。

不, 引用的就是标题块, 可以用帮助文档的请从这里开始测试一下
