### ISSUE TITLE
无序列表部分节点的折叠展开功能失效

### ISSUE THREAD

**Issue by litcu** [siyuan-note/insider#1090]
v2.3.0 alpha2和alpha3中均有该问题，往前没有留意。

如GIF所示，部分节点使用鼠标点击折叠/展开失效，点击前面的图标也无法正常显示选项。已尝试重建索引、换默认主题等方法，均无效。

![bug1](https://user-images.githubusercontent.com/53759402/194368160-1f0bc1f9-6c63-4c9a-8b40-ec8386ecc7f7.gif)

另：使用快捷键折叠展开不受影响。

**Comment by Vanessa219** [comment]
亲，麻烦把 .sy 文件导出发我下，我自己造内容按照你的录屏弄了，还是重现不了。

**Comment by Vanessa219** [comment]
你是不是缩放过？ctrl+0 再试试？

**Comment by 88250** [comment]
下个版本再看看。
