### ISSUE TITLE
移动工具栏建议

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/insider#1092]
有了这个后不错的，希望能增加样式图标，点击后进入和PC一样的工具栏，有加粗下划线那些。像格志日记这样就不错

**Comment by mozhux** [comment]
上传不了图片，好气！

**Comment by 88250** [comment]
行级元素使用划选的浮动工具栏，底部工具栏暂时不考虑，谢谢。

**Comment by 88250** [comment]
上传图片可以使用编辑区右上的 `...` 菜单。

**Comment by mozhux** [comment]
关键是移动端划线没有工具栏啊，是复制粘贴，是我操作错了吗

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月7日 11:22
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [siyuan-note/insider] 移动工具栏建议 (Issue #1092)


行级元素使用划选的浮动工具栏，底部工具栏暂时不考虑，谢谢。

―

**Comment by 88250** [comment]
使用双击后就会触发浮动工具栏，长按的话是下拉菜单。
