### ISSUE TITLE
上侧 dock 栏与下侧 dock 栏面板按钮未靠边

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/insider#1095]
如下图所示, 上侧/下侧 dock 栏位于左侧/右侧 dock 栏的上方/下方, 因此应该移除占位的空白元素
![image](https://user-images.githubusercontent.com/49649786/196000030-485e3fb9-1522-4dd2-9783-69c648d03627.png)

**Comment by Vanessa219** [comment]
考虑到该面板展开后左右两侧并没有顶到最边上，因此才留出一定空隙。
<img width="561" alt="image" src="https://user-images.githubusercontent.com/970828/196021086-9e4df2b9-f269-461f-bce0-3da39cba360b.png">
