### ISSUE TITLE
顶栏有点过肥了

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/insider#1097]
新版的顶栏宽宽的，底栏又窄窄，再加上浅色模式下黑色顶栏显得头重脚轻。
建议
1.浅色模式顶栏浅色
2.缩小顶栏宽带，大致参考office那样

**Comment by 88250** [comment]
这个暂时不改了，后面再考虑。

**Comment by mozhux** [comment]
> 这个暂时不改了，后面再考虑。
行吧，已经有人和我一样觉得黑压压
