### ISSUE TITLE
打开首个文档十分缓慢

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/insider#1103]
打开第一个文档块很慢，后续正常

https://github.com/siyuan-note/insider/assets/32903588/74737507-fa71-40c7-8ba7-a4ea926ea10e

**Comment by Vanessa219** [comment]
这个看上去和属性试图没关系，上一个版本也卡么？

**Comment by TinkMingKing** [comment]
> 这个看上去和属性试图没关系，上一个版本也卡么？

就这个版本，莫名其妙就卡，不过现在又好了，有点玄，后续我再看看，确实和属性视图没关系，先关了
