### ISSUE TITLE
属性图功能优化

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/insider#1107]
大标题与“table”的位置是不是反了，因为后续还会添加其他视图，大标题应该统领下面这些视图。
Block 是不是应该叫 Title，主题。
点击添加，默认第一个是新建文档会不会更好一些。

![image](https://github.com/siyuan-note/insider/assets/16383685/4f6679e4-a58c-413e-a3af-cde7f53094fe)

**Comment by woniuxia** [comment]
这些属性，在页面内不显示吗

**Comment by 88250** [comment]
这些设计暂时如此。属性在属性面板中显示。
