### ISSUE TITLE
特性建议：建议属性视图的筛选、排序、隐藏不在属性视图间同步。

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/insider#1109]
目前复制了属性视图后，可以在两个属性视图间同步属性，勉强解决了一部分跨表问题，但是之后还需要更直接的跨表属性，比如说克隆类型的列。但是目前复制的属性视图的显示也是同步的，大大制约了使用范围。
![图片](https://github.com/siyuan-note/insider/assets/74853597/255b490c-46cb-4237-a2b9-ea9b193ae429)
希望不要在av.json中储存这些数据，而是将这些数据储存到属性视图的块属性中

**Comment by 88250** [comment]
关联列还在考虑，这个暂时先关闭了，感谢反馈。
