### ISSUE TITLE
属性视图的2个问题

### ISSUE THREAD

**Issue by hiCaoxu** [siyuan-note/insider#1112]
![image](https://github.com/siyuan-note/insider/assets/72870110/3f4d9dd9-7b27-4001-97ac-1c1ec1c184d0)
1.左上角Block 不能更改文字；
2.右下角框中的类型为数字，输入9.0显示9

版本：当前版本 v3.0.0-alpha1 Insider Preview

**Comment by 88250** [comment]
第一个问题已有记录 https://github.com/siyuan-note/insider/issues/1110
第二个问题会自动取整，目前还没有数字格式化，后面会加入  https://github.com/siyuan-note/siyuan/issues/8764

感谢反馈。
