### ISSUE TITLE
 编辑框回车键不生效问题汇总

### ISSUE THREAD

**Issue by j1406493495** [siyuan-note/insider#1114]
数据表多处存在回车不生效问题

- 单选无法回车保存
- 无法回车添加项
- 无法回车完成字段修改

<img width="222" alt="image" src="https://github.com/siyuan-note/insider/assets/7507072/afd33716-fa18-4609-bf44-2ddd19abb9d8">

**Comment by Vanessa219** [comment]
- [x] 选择属性排序无效
- [x] 无法回车完成修改列名 ![abc592b8c59f08ff1a2b2ea2df395691](https://github.com/siyuan-note/insider/assets/970828/bea7c209-8075-44cf-b909-e27c7fd37501)
