### ISSUE TITLE
在主页面上进行单选添加项时，中文输入法按空格就自动添加项了，但此时未完成整体输入

### ISSUE THREAD

**Issue by j1406493495** [siyuan-note/insider#1115]
<img width="209" alt="image" src="https://github.com/siyuan-note/insider/assets/7507072/85178a5e-fe31-4158-a2fd-bdbdf91a6929">

**Comment by 88250** [comment]
@Vanessa219 是不是和 https://github.com/siyuan-note/insider/issues/1106 一个问题？

**Comment by Vanessa219** [comment]
是的。
