### ISSUE TITLE
在属性视图中删除后，没有同步删除块的属性。

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/insider#1118]
如题。
![图片](https://github.com/siyuan-note/insider/assets/74853597/40565b0b-4432-463b-bcd5-754a9c83a9f3)
或者是能在属性面板中进行删除？

**Comment by zxhd863943427** [comment]
另外，在属性视图中添加又删除的属性，也会在属性面板中显示。

**Comment by 88250** [comment]
属性目前暂时不考虑同步删除。

**Comment by zxhd863943427** [comment]
那么希望在属性面板上是可见的。目前删除后，属性还在，但是属性面板里不可见。

**Comment by 88250** [comment]
暂时先这样，显示出来的话无法更新也会有问题。

**Comment by zxhd863943427** [comment]
那么，能否支持在属性面板删除属性？目前只有自定义是可以删除的。

**Comment by 88250** [comment]
不支持删除和添加，这个等稳定以后再考虑看看能否支持。
