### ISSUE TITLE
 在数据库主键中点击打开文档块后，鼠标放在引用块上，无法出现页面预览

### ISSUE THREAD

**Issue by j1406493495** [siyuan-note/insider#1121]

**Comment by 88250** [comment]
我这里测试正常：

[视频.webm](https://github.com/siyuan-note/insider/assets/873584/6060c662-c378-4787-ada9-c314a9c534a2)

**Comment by 88250** [comment]
暂时先关闭了，如果有进一步信息麻烦回帖，谢谢。
