### ISSUE TITLE
当前笔记本中关系图不生效（在另一个笔记本中是生效的）

### ISSUE THREAD

**Issue by j1406493495** [siyuan-note/insider#1122]
<img width="1012" alt="image" src="https://github.com/siyuan-note/insider/assets/7507072/3ab4e31f-1e40-428e-bdba-1f9cf423b4c0">

<img width="1008" alt="image" src="https://github.com/siyuan-note/insider/assets/7507072/99ceb787-87d0-453b-b30d-b83c03d67406">

**Comment by 88250** [comment]
看一下过滤条件。

**Comment by j1406493495** [comment]
是指这个吗？
<img width="1006" alt="image" src="https://github.com/siyuan-note/insider/assets/7507072/b25fad17-1fb3-46bf-9ffa-4a4ce0d39da2">

**Comment by 88250** [comment]
我这里没有问题：

![image](https://github.com/siyuan-note/insider/assets/873584/2314cc5e-ab28-4881-916f-79c33f57cd97)

你看下 Console 中是否有报错，感觉是被某个插件影响了。

**Comment by j1406493495** [comment]
不是插件的原因，是日记。在日记中的关系图出不来，我把文件移出日记，就可以了

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/insider/assets/873584/bde61708-0b8e-4bef-ac0c-dcd1da326d6f)

**Comment by j1406493495** [comment]
乌龙了。。。
