### ISSUE TITLE
【【输入中文引用创建文档后，再输入‘，’号，‘，’号和光标会变到文字前方

### ISSUE THREAD

**Issue by j1406493495** [siyuan-note/insider#1123]
<img width="608" alt="image" src="https://github.com/siyuan-note/insider/assets/7507072/6360bf9e-0330-4767-a682-2311e8413b51">

<img width="225" alt="image" src="https://github.com/siyuan-note/insider/assets/7507072/6439fd0d-3eeb-4d96-aadd-21125652667d">

**Comment by 88250** [comment]
我这里无法重现问题，用的是搜狗拼音。

**Comment by j1406493495** [comment]
引用的时候，要新建文档，现有的块没有问题。
我用的是 Mac，微信输入法，双拼模式

<img width="689" alt="image" src="https://github.com/siyuan-note/insider/assets/7507072/752f7571-0a47-4d33-bc1f-18871b15a0e9">

**Comment by 88250** [comment]
能换个输入法测试看看吗？

**Comment by j1406493495** [comment]
用原生输入法没问题，看来应该是微信输入法的问题了

**Comment by 88250** [comment]
输入法的兼容性关联到这里 https://github.com/siyuan-note/siyuan/issues/4826 感谢反馈。
