### ISSUE TITLE
改善 URL 为思源协议或内部资源链接时的交互

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/insider#1124]
### In what scenarios do you need this feature?

目前新的url类型把原有的“打开”变为了“复制”，且点击cell不是编辑而是变为打开，这使得编辑url变得困难，且失去了两个重要的功能：块预览和打开内部资源。

目前在url类型上无法实现悬浮预览内部的块，同时粘贴资源链接后，点击打开会跳转到浏览器下载，而不是在思源内部打开，功能大大下降了。

### Describe the optimal solution

希望能够在增加“复制”按钮的同时保留原有的功能逻辑，这个我看了下源码，并不是太困难，如果官方同意我可以pr。

**Comment by TinkMingKing** [comment]
那我+1，复制没意义，我都能跳转了，还怕在浏览器不能复制吗，能编辑也能复制，复制有啥意义……徒增操作成本，感觉复制能够直接去掉，顺带一提，整列悬浮都显示打开按钮的逻辑有点奇怪，悬浮在cell里显示就好了吧？

**Comment by Vanessa219** [comment]
这个是参照了 notion 后修改的，可能大部分用户填入后就很少会进行修改。

**Comment by zxhd863943427** [comment]
notion的操作逻辑可以保留，但我更希望能保留悬浮预览和打开内部资源。

如果无法实现，那我情愿使用之前的版本，这样不会丢弃思源的优势。

**Comment by TinkMingKing** [comment]
那倒也是，确实不怎么会去修改，是我考虑不周了

**Comment by Vanessa219** [comment]
> notion的操作逻辑可以保留，但我更希望能保留悬浮预览和打开内部资源。
> 
> 如果无法实现，那我情愿使用之前的版本，这样不会丢弃思源的优势。

指的是 `siyuan://blocks/xxx` 这样的链接么？

**Comment by zxhd863943427** [comment]
实际上是两种，assets/xxx的内部资源链接和siyuan://blocks/xxx的内部块链接。

在之前的实现中，可以悬浮预览siyuan://blocks/xxx的内部块链接，并且直接打开assets/xxx的内部资源链接。

更新后，无法悬浮预览siyuan://blocks/xxx，同时点击assets/xxx的内部资源链接会跳转到浏览器下载。

在保留目前的操作逻辑下修改了点击事件的pr已提交到 https://github.com/siyuan-note/siyuan/pull/8937

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/pull/8937/files
