### ISSUE TITLE
概率出现文档无法打开问题

### ISSUE THREAD

**Issue by j1406493495** [siyuan-note/insider#1125]
<img width="1002" alt="image" src="https://github.com/siyuan-note/insider/assets/7507072/77c8706e-6f2f-4884-9525-058eac5e88a8">

<img width="993" alt="image" src="https://github.com/siyuan-note/insider/assets/7507072/95c004e5-7138-4222-ae78-53c2cd08722b">

**Comment by 88250** [comment]
关闭插件试试 
![image](https://github.com/siyuan-note/insider/assets/873584/28e25d99-0a32-4eac-8838-603eee9c33ed)
