### ISSUE TITLE
关于数据库表格 Block 字段的问题

### ISSUE THREAD

**Issue by idea-zone** [siyuan-note/insider#1128]
1. Block 字段，在同一个 Table 中，无法将同一个文档，关联到两个不同的行上。
2. 如果上述为了唯一性考虑而不能修改的话，是否可以增加一个 `页面` 字段，点击后可以打开其他页面。 
3. 也可以是对 `链接` 字段进行修改：
    * 链接字段目前是可以打开 `siyuan://` 链接的。但希望可以显示为标题名，而不是链接地址。
    * 链接字段是否可以增加右键菜单“清空”： 把输入的链接内容删除了。现在输入正确的链接地址后 ，点击就是跳转，无法再次编辑。

![image](https://github.com/siyuan-note/insider/assets/53116704/3988ff5b-e44c-429a-951b-f3e08e5b099e)

**Comment by 88250** [comment]
1. 嗯，为了唯一性考虑，不支持重复插入相同的块
2. 请关注 引用列 https://github.com/siyuan-note/siyuan/issues/9305
3. 链接列 仅支持地址；编辑问题下个版本修复 https://github.com/siyuan-note/siyuan/issues/9632

感谢反馈。

**Comment by 88250** [comment]
后面截图的情况是因为第一行是行关联到块了，第二行是普通的行，没有关联块。
