### ISSUE TITLE
Siyuan 数据库 的一些建议

### ISSUE THREAD

**Issue by idea-zone** [siyuan-note/insider#1130]
- [ ] 增加文字居中等右键菜单
- [ ] 多选类型，前景色和背景色对比可以变强一些
- [ ] 仅删除数据库行和 Block 文档的关联
- [ ] 数据库过滤支持 And 和 Or 选项，(最好可以增加 Group 的方式)
- [ ] 文本属性列，是否可以支持简单的 markdown 标记渲染或者常见的属性

以下是详细说明：

### 1.  当开启换行选项时，文字默认靠左居上，是否可以支持和普通表格一样文字水平居中、垂直居中等菜单选项开关.
![换行](https://github.com/siyuan-note/insider/assets/53116704/4bcc178d-e14d-4b04-a119-ff3155b57c37)
![表格](https://github.com/siyuan-note/insider/assets/53116704/070080db-7bfd-4b94-9cb4-2fd326d76096)
###  2. `多选` 类型文本和背景颜色相近，分别起来不太容易。
![image](https://github.com/siyuan-note/insider/assets/53116704/6706d2f0-142d-444f-ad84-58924305efdc)
可以尝试这样（不是说要这种配色，只是文字和背景色的对比度可以这样试试）
![image](https://github.com/siyuan-note/insider/assets/53116704/45f75e59-a1e3-42ee-aa47-07f6a57dc253)

### 3.  当关联到某一行的时候，是否可以提供接口，仅删除 “文档”和当前 “行” 的关联，而不删除数据中的行的记录。
![image](https://github.com/siyuan-note/insider/assets/53116704/d1faac36-27dc-4e43-8afc-4ba6e81620da)

### 4.  数据库过滤条件是否可以支持 And 和 Or  组合：
![image](https://github.com/siyuan-note/insider/assets/53116704/0c983b0f-6d41-4ab4-9731-dfffc5c62ecd)

### 5. 如果创建行是有筛选条件，可以自动填充符合条件的值到对应的属性字段上
![image](https://github.com/siyuan-note/insider/assets/53116704/fbb3201c-5b88-4f8a-be7c-0ae6e5af2780)

### 6. 文本属性列，是否可以支持简单的 markdown 解析，至少支持 粗体、斜体、删除线、上标、下标、行内代码块，高亮 格式。

**Comment by 88250** [comment]
1. 当前的纯文本列暂时不考虑做排版
2. 默认主题下还好
3. https://github.com/siyuan-note/siyuan/issues/9892
4. 暂时不考虑
5. 暂时不考虑
6. 同 1

感谢反馈。

**Comment by 88250** [comment]
5. https://github.com/siyuan-note/siyuan/issues/9905
