### ISSUE TITLE
数据库自定义模板问题 : key not found v12.12.0

### ISSUE THREAD

**Issue by idea-zone** [siyuan-note/insider#1132]
1. 在模板中创建多个数据库视图时，应用模板会第二个模板会出现 key not found 报错。
2. 同时，在模板中添加的过滤条件、排序条件，在应用模板的时候也没了。

![image](https://github.com/siyuan-note/insider/assets/53116704/0cec038a-b9e2-4ab8-9fc7-6051639177cd)
![image](https://github.com/siyuan-note/insider/assets/53116704/0fb28939-3628-49a5-abb1-e73a247b2d12)

**Comment by 88250** [comment]
默认是导出当前文档创建的吗？

**Comment by 88250** [comment]
已经找到问题了，下个版本修复，谢谢。
