### ISSUE TITLE
数据库：换行选项失去作用

### ISSUE THREAD

**Issue by idea-zone** [siyuan-note/insider#1133]
![image](https://github.com/siyuan-note/insider/assets/53116704/4d676fef-e62d-457a-b585-d8a660617406)

**Comment by 88250** [comment]
从截图没有看出问题，另外，麻烦在默认主题下测试。

**Comment by idea-zone** [comment]
> 从截图没有看出问题，另外，麻烦在默认主题下测试。
以下是默认主题(daylight)下的测试： 
老版本的标题行，如果启用换行，会显示为，
“
计划
番茄
”
现在的标题行显示的是 “计划...”  。“计划”后面的直接没有。

![默认主题下换行问题](https://github.com/siyuan-note/insider/assets/53116704/9373300e-f187-4a64-b691-bca5b82d480e)

**Comment by 88250** [comment]
这里的 换行 指的是单元格值换行，不是列名哦。
