### ISSUE TITLE
数据库：第二个Table，在有筛选条件下，新建行无法自动按条件填充字段

### ISSUE THREAD

**Issue by idea-zone** [siyuan-note/insider#1134]
![image](https://github.com/siyuan-note/insider/assets/53116704/98cc3a28-8f22-4160-9ada-ca2d51863837)
![image](https://github.com/siyuan-note/insider/assets/53116704/5e373a32-fd6b-4d01-be73-1f26106ee49b)

补充：
1.  IndexWork （第一个Table）也有筛选条件，筛选条件是：
![image](https://github.com/siyuan-note/insider/assets/53116704/a92bfee1-5ab9-418c-9032-6d0ba2adc994)

**Comment by 88250** [comment]
你好，我这里测试无法重现问题，请看录屏：

[issue.webm](https://github.com/siyuan-note/insider/assets/873584/81400591-4604-411a-9bff-62c3e9077b05)

如果在默认主题下可以重现，方便的话请把该文档导出 .sy.zip 发送给我们 845765@qq.com 

我暂时关闭问题了，谢谢。

**Comment by idea-zone** [comment]
> 你好，我这里测试无法重现问题，请看录屏：
> 
>  issue.webm 
> 如果在默认主题下可以重现，方便的话请把该文档导出 .sy.zip 发送给我们 [845765@qq.com](mailto:845765@qq.com)
> 
> 我暂时关闭问题了，谢谢。

这个问题很奇怪，我测试了默认主题确实没有问题，切换回来自己的主题居然也没问题了。暂时不知道是哪里出问题了。
唯一不同的操作就是，把表格相关的样式注释后，再开放出来。先这样，程序能跑了。感谢。
